apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: socialflow

resources:
  - ../../base
  - ../../base/worker-hpa.yaml

commonLabels:
  app.kubernetes.io/part-of: socialflow
  app.kubernetes.io/environment: dev

images:
  - name: socialflow-backend
    newTag: dev
  - name: socialflow-worker
    newTag: dev
